import abc
import types
from _typeshed import Incomplete
from abc import abstractmethod
from book_tools.format.bookfile import BookFile as BookFile
from book_tools.format.mimetype import Mimetype as Mimetype
from book_tools.format.util import list_zip_file_infos as list_zip_file_infos

class FB2StructureException(Exception):
    def __init__(self, error) -> None: ...

class Namespace:
    FICTION_BOOK20: str
    FICTION_BOOK21: str
    XLINK: str

class FB2Base(BookFile, metaclass=abc.ABCMeta):
    description: Incomplete
    def __init__(self, file, original_filename, mimetype) -> None: ...
    @abstractmethod
    def __create_tree__(self): ...
    def extract_cover_internal(self, working_dir): ...
    def extract_cover_memory(self): ...

class FB2(FB2Base):
    def __init__(self, file, original_filename) -> None: ...
    def __create_tree__(self): ...
    def __exit__(self, kind: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class FB2Zip(FB2Base):
    def __init__(self, file, original_filename) -> None: ...
    def __create_tree__(self): ...
    def __exit__(self, kind: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class FB2Base_new(metaclass=abc.ABCMeta):
    def __init__(self, file, original_filename, mimetype) -> None: ...
    @abstractmethod
    def __create_tree__(self, file): ...
    def parse_book_data(self, file, original_filename, mimetype) -> BookFile: ...
    def extract_cover_internal(self, working_dir): ...
    def extract_cover_memory(self): ...

class FB2_new(FB2Base_new):
    def __init__(self, file, original_filename) -> None: ...
    def __create_tree__(self, file): ...
    def __exit__(self, kind: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class FB2Zip_new(FB2Base_new):
    def __init__(self, file, original_filename) -> None: ...
    def __create_tree__(self, file): ...
    def __exit__(self, kind: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
