import io
import types
from _typeshed import Incomplete
from book_tools.format.bookfile import BookFile as BookFile
from book_tools.format.mimetype import Mimetype as Mimetype
from book_tools.format.util import strip_symbols as strip_symbols

class fb2tag:
    tags: Incomplete
    attrs: Incomplete
    attrss: Incomplete
    index: int
    size: Incomplete
    values: Incomplete
    process_value: bool
    current_value: str
    def __init__(self, tags) -> None: ...
    def reset(self) -> None: ...
    def tagopen(self, tag: str, attrs=[]) -> bool: ...
    def tagclose(self, tag) -> None: ...
    def setvalue(self, value) -> None: ...
    def getvalue(self): ...
    def gettext(self, divider: str = '\n'): ...
    def getattr(self, attr): ...
    def getattrs(self, attr): ...

class fb2cover(fb2tag):
    iscover: bool
    cover_name: str
    isfind: bool
    def __init__(self, tags) -> None: ...
    def reset(self) -> None: ...
    def tagopen(self, tag, attrs=[]): ...
    def tagclose(self, tag) -> None: ...
    def setcovername(self, cover_name) -> None: ...
    def add_data(self, data) -> None: ...
    @property
    def cover_data(self): ...
    @cover_data.setter
    def cover_data(self, value) -> None: ...

class fb2parser:
    rc: Incomplete
    author_first: Incomplete
    author_last: Incomplete
    genre: Incomplete
    lang: Incomplete
    book_title: Incomplete
    annotation: Incomplete
    docdate: Incomplete
    series: Incomplete
    cover_name: Incomplete
    cover_image: Incomplete
    stoptag: str
    process_description: bool
    parse_error: int
    parse_errormsg: str
    def __init__(self, readcover: int = 0) -> None: ...
    def reset(self) -> None: ...
    def start_element(self, name, attrs) -> None: ...
    def end_element(self, name) -> None: ...
    def char_data(self, data) -> None: ...
    def parse(self, f, hsize: int = 0) -> None: ...

class FB2StructureException(Exception):
    def __init__(self, error) -> None: ...

class FB2sax(BookFile):
    fb2parser: Incomplete
    description: Incomplete
    def __init__(self, file, original_filename) -> None: ...
    def extract_cover_memory(self): ...
    def __exit__(self, kind: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class FB2sax_new:
    fb2parser: Incomplete
    def __init__(self, file, original_filename) -> None: ...
    def parse_book_data(self, file: io.BytesIO, original_filename: str) -> BookFile: ...
    def extract_cover_memory(self): ...
    def __exit__(self, kind: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
