import types
from _typeshed import Incomplete
from book_tools.format.bookfile import BookFile as BookFile
from book_tools.format.mimetype import Mimetype as Mimetype
from book_tools.pymobi.mobi import BookMobi as BookMobi

class Mobipocket(BookFile):
    description: Incomplete
    def __init__(self, file, original_filename) -> None: ...
    def __exit__(self, kind: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def get_encryption_info(self): ...
    def extract_cover_internal(self, working_dir): ...
    def extract_cover_memory(self): ...

class Mobipocket_new:
    def __init__(self, file, original_filename) -> None: ...
    def __exit__(self, kind: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def parse_book_data(self, file, original_filename): ...
    def get_encryption_info(self): ...
    def extract_cover_internal(self, working_dir): ...
    def extract_cover_memory(self): ...
