import types
from book_tools.format.bookfile import BookFile as BookFile

class Dummy(BookFile):
    def __init__(self, file, original_filename, mimetype) -> None: ...
    def __exit__(self, kind: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class Dummy_new:
    def __init__(self, file, original_filename, mimetype) -> None: ...
    def parse_book_data(self, file, original_filename, mimetype) -> BookFile: ...
    def __exit__(self, kind: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
